---
title: "ASPE - Traitements sur les IPR"
author: "Pascal Irz"
date: "`r format(Sys.time(), 'Le %d %B %Y')`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


# Chargement des packages et des données

```{r}
library(aspe)
library(tidyverse)
```


```{r, eval = FALSE}
load(file = "processed_data/toutes_tables_aspe_sauf_mei.RData")
```

```{r, echo = FALSE}
load(file = "../processed_data/toutes_tables_aspe_sauf_mei.RData")
```



```{r}
passerelle <- mef_creer_passerelle()
```


On peut sélectionner uniquement les opérations réalisées dans le cadre des réseaux.

```{r}
passerelle <- passerelle %>%
  aspe::mef_select_obj(objectif = 2:7)
```

Sélection de la période d'étude et ajout des IPR.

```{r}
ipr <- passerelle %>% 
  mef_ajouter_ipr() %>% 
  left_join(y = ref_objectif %>% select(obj_id, obj_libelle)) %>% 
  mef_ajouter_ope_date() %>% 
  filter(ope_date > lubridate::dmy("01/01/2010"),
         ope_date < lubridate::dmy("31/12/2020")) %>% 
  droplevels()
```

Nombre d'opérations avec IPR selon le réseau.
NB: une même opération peut être répertoriée sur plusieurs réseaux.

```{r}
ipr %>% 
  filter(ipr > 0) %>% 
  droplevels() %>% 
  group_by(annee, obj_libelle) %>% 
    summarise(n_pop = n_distinct(pop_id)) %>% 
  pivot_wider(names_from = obj_libelle, values_from = n_pop) %>% 
  View
```






















